### PR TITLE
Pass the error including stacktrace to error handlers and reporters

### LINKED ISSUE #1728: Browser error handling loses information.
The browser onerror handler has multiple arguments:
```js
window.onerror = function(message, source, lineno, colno, error) { ... }
```
But jasmine seems to defeat the feature by only passing a single argument 
```js
QueueRunner.prototype.execute = function() {
    var self = this;
    this.handleFinalError = function(error) {
      self.onException(error);
    };
    this.globalErrors.pushListener(this.handleFinalError);
    this.run(0);
  };
```

Then only the last handler is used:
```js
    var onerror = function onerror() {
      var handler = handlers[handlers.length - 1];

      if (handler) {
        handler.apply(null, Array.prototype.slice.call(arguments, 0));
      } else {
        throw arguments[0];
      }
    };
```

How can we get the full stack?

### PR DESCRIPTION
**Pull request by prantlf**
## Description

Instead of the string with the error message, pass the `Error` instance, which includes both the message and the stacktrace.

## Motivation and Context

Attempts to fix #1728.

The [global window error handler](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror#window.onerror) is used to handle errors thrown from within asynchronous functions and tests. The first parameter is the error message only; the fifth parameter is the full error object including the stacktrace. Using the error object instead of the error message lets the reporters log it. (Searching for the first occurrence of an error instance in arguments to work with browsers, which may not comply with the HTML5 standard.)

## How Has This Been Tested?

I created a [minimum project `bug-jasmine-no-async-stacktrace` using `karma`](https://github.com/prantlf/bug-jasmine-no-async-stacktrace) to reproduce the issue and demonstrate the effect of this fix.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/core/GlobalErrors.js [hunk 1]
```diff
@@ -7,7 +7,12 @@ getJasmineRequireObj().GlobalErrors = function(j$) {
       var handler = handlers[handlers.length - 1];
 
       if (handler) {
-        handler.apply(null, Array.prototype.slice.call(arguments, 0));
+        // Get error from (message, source, lineno, colno, error)
+        var args = Array.prototype.slice.call(arguments, 0);
+        var error = args.find(function(arg) {
```
Comment (sgravrock) [inline src/core/GlobalErrors.js]: Unfortunately `find` isn't available on all the environments Jasmine supports (IE comes to mind).

Comment (prantlf) [reply src/core/GlobalErrors.js]: It's true. I'm going to push another solution. Instead of looking for the first error instance, let's try using the [documented interface](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror#Syntax). If the browser doesn't send all parameters or the last parameter is no error, do what the previous coded did for compatibility.

**Comment by slackersoft** [comment]
Unfortunately, `Env` relies on getting the full arguments passed along as is currently done in the base handler. It looks like the extra information is _actually_ being lost inside `QueueRunner`s `handleFinalError` function. I think it would make sense to move this logic into there instead of losing the additional arguments if the browser supplies us with an error as this is currently implemented.

**Comment by prantlf** [comment]
I see. Originally I dropped the full parameter list in the global error handling to make the interface stable since that point already, but it would break existing handlers.

I've pushed the solution as you prefer it now. Global error handlers continue getting all parameters as the browser or other JavaScript engine sent them and can deal with them, as they did. The error handler passed to the `QueueRunner` will get a single parameter, as it always have, and that will be preferably the error instance now, which includes a call stack.

What do you think, @slackersoft?
